SPACE:
  NAME: 'nasbench201' # (nasbench201, nasbench301, nasbenchmacro)
  CHANNELS: 16
  LAYERS: 5
  NODES: 4
# BENCHMARK:

LOADER:
  DATASET: 'cifar10'
  DATAPATH: 'data'
  SPLIT: [0.7, 0.3]
  BATCH_SIZE: 32
  NUM_CLASSES: 10
SEARCH:
  IM_SIZE: 32
  batch_size: 64
  data_size: 25000
  cutout: False
  cutout_length: 16
  cutout_prob: 1.0
  train_portion: 0.9
  AUTO_RESUME: False
  WEIGHTS: 'exp/one_shot_nasbench201_SPOS/checkpoints/model_epoch_0001.pyth'
  method_type: FairNAS
  ALL_NOT_BN: 0
OPTIM:
  MAX_EPOCH: 400
  LR_POLICY: 'cos'
  MIN_LR: 0.0
  BASE_LR: 0.025
  WEIGHT_DECAY: 0.0003
DARTS:
  UNROLLED: False
  ALPHA_LR: 3.e-4
  ALPHA_WEIGHT_DECAY: 1.e-3
TRAIN:
  AUX_WEIGHT: 0
  LAYERS: 8
  CHANNELS: 32
evaluation:
  train_portion: 1.
experiment_type: single
test_arch_num: 200
train_size_single: 0
train_size_list: [0]
fidelity_single: 5
fidelity_list: [1, 2, 3, 5, 7, 9, 13, 19, 26, 37, 52, 73]
max_hpo_time: 0
uniform_random: 1
OUT_DIR: 'exp/oneshot'
RNG_SEED: 1000
only_train: 0
all_arch: 0